config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :workouts
  resources :meals

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  validates :title, :meal_details, presence: true
  validates :month,  numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 12 }
  validates :day,  numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 31 }
  validates :year,  numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  validates :title, :workout_details, presence: true
  validates :month,  numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 12 }
  validates :day,  numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 31 }
  validates :year,  numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :duration,  numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :intensity, format: { with: /\A(Easy|Medium|Hard|easy|medium|hard)\z/,
    message: "only accepts Easy, Medium or Hard" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meal = Meal.all
  end  
  
  def new
    @meal = Meal.new
  end
  
  def edit
    @meal = Meal.find(params[:id])
  end
  
  def create
    @meal = Meal.new(meal_params)
    
    if @meal.save
      redirect_to @meal
    else
      render 'new'
    end
  end
  
  def show
    @meal = Meal.find(params[:id])
  end
  
 
  
  
  def update
    @meal = Meal.find(params[:id])
    if @meal.update(meal_params)
      redirect_to @meal
    else
      render 'edit'
    end
  end
  
  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy
 
    redirect_to meals_path
  end
  
  private
    def meal_params
      params.require(:meal).permit(:title, :date, :day, :month, :year,  :meal_details)
    end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  require "date"  
  def index
    current = DateTime.now
    @meal = Meal.where("#{current.day}=day AND month=#{current.month} AND year=#{current.year}")
    @workout = Workout.where("day==#{current.day} AND month==#{current.month} AND year==#{current.year}")
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def index
    @workout = Workout.all
  end  
  
  def new
    @workout = Workout.new
  end
  def edit
    @workout = Workout.find(params[:id])
  end
  def create
    @workout = Workout.new(workout_params)
    
    if @workout.save
      redirect_to @workout
    else
      render 'new'
    end
  end
  def show
    @workout = Workout.find(params[:id])
  end
  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy
 
    redirect_to workouts_path
  end
  
  def update
    @workout = Workout.find(params[:id])
    if @workout.update(workout_params)
      redirect_to @workout
    else
      render 'edit'
    end
  end
  
  private
  def workout_params
    params.require(:workout).permit(:title, :workout_type, :day, :month, :year, :workout_date, :duration, :intensity,  :workout_details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExerciseLogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= "#{controller_name } #{action_name }" %>'>

<%= yield %>

</body>
</html>

app/views/meals/_footer.html.erb
<div id = "footer">
  <p> Copy right Soti </p>
</div>

app/views/meals/_form.html.erb
<%= form_for @meal do |f| %>
 
  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@meal.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @meal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div id="form-wrapper" class="clearfix">
	  <div id="main">
	    <p>
	      <%= f.label :title %><br>
	      <%= f.text_field :title %>
	    </p>
	   
	    <p>
	      <%= f.label :day %><br>
	      <%= f.text_field :day %><br>
	      <%= f.label :month %><br>
	      <%= f.text_field :month %><br>
	      <%= f.label :year %><br>
	      <%= f.text_field :year %><br>
	    </p>
	  </div>
	  <div id="details">
	    <p>
	      <%= f.label :meal_details  %><br>
	      <%= f.text_area :meal_details %>
	    </p>    
	  </div>
  </div>
  <p>
    <%= f.submit %>
  </p>
    
 <% end %>

app/views/meals/edit.html.erb
<div id="container">
  <div id="header">
    <h1>Editing meal</h1>
  </div>
  <div id="form">
    <%= render 'form' %>
  </div>
  <div = id="nav">
    <%= link_to 'Back', meals_path %>
  </div>
  <%= render 'footer' %>
</div>

app/views/meals/index.html.erb
<div id = "container">

<div id = "header">
<h1>Listing meal</h1>
</div>

<div id = "content">
<table>
 
    <tr class="first_row">
      <th>Title</th>
      <th>Day</th>
      <th>Month</th>
      <th>Year</th>
    </tr>
  
  <% @meal.each do |meal| %>
    <tr>
      <td><%= meal.title %></td>
      <td><%= meal.day %></td>
      <td><%= meal.month %></td>
      <td><%= meal.year %></td>
      <td><%= link_to 'Show', meal_path(meal) %></td>
      <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
      <td><%= link_to 'Destroy', meal_path(meal),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
</div>
<div id = "nav">
<%= link_to 'New meal', new_meal_path %>
<%= link_to 'Home page', controller: 'welcome' %>
</div>
    <%= render 'footer' %>
</div>

app/views/meals/new.html.erb
<div id="container">
  <div id="header">
    <h1>New meal</h1>
  </div>
  <div id="form">
    <%= render 'form' %>
  </div>
  <div id="nav">
    <%= link_to 'Back', meals_path %>
  </div>
  <%= render 'footer' %>
</div>

app/views/meals/show.html.erb
<head>
  <title>Saved meal</title>
</head>

  <div id = "container">
    <div id = "header">
      <h1>Saved meal</h1>
    </div>
   
    <div id = "main">
      <p>
        <strong>Title:</strong>
        <%= @meal.title %>
      </p>
  
      <p>
        <strong>Date:</strong>
        <%= @meal.day.to_s + "-" + @meal.month.to_s + "-" + @meal.year.to_s %>
      </p> 
     </div> 
     
     <div id = "details">
        <p>
          <strong>Text:</strong>
          <%= @meal.meal_details %>
        </p>
     </div>
	   
    <div id = "nav">     
     <%= link_to 'Back', meals_path %>
     <%= link_to 'Home', controller: 'welcome' %>
    </div>
    <%= render 'footer' %>
  </div>

app/views/welcome/_footer.html.erb
<div id = "footer">
  <p> Copy right Soti </p>
</div>

app/views/welcome/index.html.erb
<div id = "container">

<div id = "header">
  <h1>Meal and Fitness Blogger</h1>
  
</div>
<div id = "content">
<h2>Today's logs</h2>

<table>
  <tr><th><h3>Today's meals</h3></th></tr>
  <tr class="first_row">
    <th>Title</th>
    <th>Day</th>
    <th>Month</th>
    <th>Year</th>
  </tr>
      <% @meal.each do |meal| %>
      <tr>
      <td><%= meal.title %></td>
      <td><%= meal.day %></td>
      <td><%= meal.month %></td>
      <td><%= meal.year %></td>
      <td><%= link_to 'Show', meal_path(meal) %></td>
      <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
      <td><%= link_to 'Destroy', meal_path(meal),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
      <% end %>
</table>
<table>
<tr><th><h3>Today's workouts</h3></th></tr>
  <tr class="first_row">
    <th>Title</th>
    <th>Day</th>
    <th>Month</th>
    <th>Year</th>
  </tr>
  
  <% @workout.each do |workout| %>
    <tr>
      <td><%= workout.title %></td>
      <td><%= workout.day %></td>
      <td><%= workout.month %></td>
      <td><%= workout.year %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>
      <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
      <td><%= link_to 'Destroy', workout_path(workout),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
   <% end %>  
</table>

</div>
<div id = "nav">
  
  <%= link_to 'Workouts', controller: 'workouts' %>
  
  
    <%= link_to 'Meals', controller: 'meals' %>
  

</div>
    <%= render 'footer' %>
</div>

app/views/workouts/_footer.html.erb
<div id = "footer">
  <p> Copy right Soti </p>
</div>

app/views/workouts/_form.html.erb
<%= form_for @workout do |f| %>
 
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@workout.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @workout.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <div = id="main">
 
    <%= f.label :title %>
    <%= f.text_field :title %>
 
 
  
    <%= f.label :type %>
    <%= f.text_field :workout_type %>
  
  
  
    <%= f.label :duration %>
    <%= f.text_field :duration %>
    
  
  
    <%= f.label :intensity %>
    <%= f.text_field :intensity %>
  
   
  
    <%= f.label :day %>
    <%= f.text_field :day %>
    <%= f.label :month %>
    <%= f.text_field :month %>
    <%= f.label :year %>
    <%= f.text_field :year %>
  
 </div>
 <div = id="details">
  
    <%= f.label :workout_details %>
    <%= f.text_area :workout_details %>
  

 </div>
  
    <%= f.submit %>
  
 
<% end %>

app/views/workouts/edit.html.erb
<div id="container">
  <div id="header">
    <h1>Editing workout</h1>
  </div>
  <div id="form">
    <%= render 'form' %>
  </div>
  <div = id="nav">
    <%= link_to 'Back', workouts_path %>
  </div>
  <%= render 'footer' %>
</div>

app/views/workouts/index.html.erb
<div id = "container">

<div id = "header">
<h1>Listing workouts</h1>
</div>
<div id = "content"> 
<table>
  <tr class="first_row">
    <th>Title</th>
    <th>Type</th>
    <th>Intensity</th>
    <th>Duration</th>
    <th>Day</th>
    <th>Month</th>
    <th>Year</th>
  </tr>
 
  <% @workout.each do |workout| %>
    <tr>
      <td><%= workout.title %></td>
      <td><%= workout.workout_type %></td>
      <td><%= workout.intensity %></td>
      <td><%= workout.duration %></td>
      <td><%= workout.day %></td>
      <td><%= workout.month %></td>
      <td><%= workout.year %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>
      <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
      <td><%= link_to 'Destroy', workout_path(workout),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
</div>
<div id = "nav">
<%= link_to 'New workout', new_workout_path %>
<%= link_to 'Home page', controller: 'welcome' %>

  <%= render 'footer' %>
 </div>

app/views/workouts/new.html.erb
<div id="container">
  <div id="header">
    <h1>New workout</h1>
  </div>
  <div id="form">
    <%= render 'form' %>
  </div>
  <div id="nav">
    <%= link_to 'Back', workouts_path %>
  </div>
  <%= render 'footer' %>
</div>

app/views/workouts/show.html.erb
<head>
  <title>Saved workout</title>
</head>
<div id = "container">
    <div id = "header">
      <h1>Saved workout</h1>
    </div>
  <div id = "main">  
  <p>
    <strong>Title:</strong>
    <%= @workout.title %>
  </p>
  <p>
    <strong>Type:</strong>
    <%= @workout.workout_type %>
  </p>
  <p>
    <strong>Date:</strong>
    <%= @workout.day.to_s + "-" + @workout.month.to_s + "-" + @workout.year.to_s %>
  </p> 
  
  <p>
    <strong>Duration:</strong>
    <%= @workout.duration %>
  </p>
  
  <p>
    <strong>Intensity:</strong>
    <%= @workout.intensity %>
  </p>  
  </div>
  <div id = "details">
  <p>
    <strong>Text:</strong>
    <%= @workout.workout_details %>
  </p> 
  </div>
  <div id = "nav">
    <%= link_to 'Back', workouts_path %>
    <%= link_to 'Home', controller: 'welcome' %>
  </div>
  <%= render 'footer' %>
 </div>